title: "A Blog Title"
description: "A log of random projects."
# theme: minima
remote_theme: jekyll/minima

header_pages:
  - _pages/about.md
  - _pages/archive.md

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: auto
