name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install markdownlint
        run: |
          npm install -g markdownlint-cli

      - name: Run markdown lint
        run: |
          markdownlint "**/*.md"

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install cspell
        run: |
          npm install -g cspell

      - name: Run spell check
        run: |
          cspell "**/*.md" || echo "Some spelling errors detected. Review the log for details."

  validate-yaml-front-matter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Validate front matter
        run: |
          for file in _posts/*.md; do
            if ! grep -q "title:" "$file" || ! grep -q "date:" "$file"; then
              echo "Error: Missing required front matter fields in $file"
              exit 1
            fi
          done
