name: Publish Drafts

on:
  push:
    paths:
      - "_drafts/**" # Trigger the workflow when drafts are modified

jobs:
  publish_drafts:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Set to your Ruby version

    - name: Find drafts to publish
      run: |
        mkdir -p _posts
        for file in _drafts/*.md; do
          if grep -q "published: true" "$file"; then
            # Extract date for the new filename
            today=$(date +%Y-%m-%d)
            filename=$(basename "$file")
            mv "$file" "_posts/${today}-${filename}"
            echo "Moved $file to _posts/${today}-${filename}"
          fi
        done

    - name: Commit and push published posts
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add _posts/*.md
        git commit -m "Auto-publish drafts"
        git push
