name: Publish Drafts

on:
  push:
    paths:
      - "_drafts/**"

jobs:
  publish_drafts:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Check for published drafts
      id: check_published
      run: |
        if grep -rl "published: true" _drafts/*.md; then
          echo "found=true" >> $GITHUB_ENV
        else
          echo "found=false" >> $GITHUB_ENV
        fi

    - name: Skip if no drafts to publish
      if: env.found == 'false'
      run: echo "No drafts marked for publishing. Skipping."

    - name: Find drafts to publish
      if: env.found == 'true'
      run: |
        today=$(date +"%Y-%m-%d")
        for file in _drafts/*.md; do
          if grep -q "published: true" "$file"; then
            filename=$(basename "$file")
            mv "$file" "_posts/${today}-${filename}" && echo "Moved $file to _posts/${today}-${filename}"
          fi
        done

    - name: Commit changes to a new branch
      if: env.found == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b auto-publish-drafts
        git add _posts/*.md
        git commit -m "Auto-publish drafts on $(date +'%Y-%m-%d')"
        git push -u origin auto-publish-drafts

    - name: Create a pull request
      if: env.found == 'true'
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: auto-publish-drafts
        base: main
        title: "Publish Drafts"
        body: "This PR contains drafts marked as ready to publish."
