name: Publish Drafts

on:
  push:
    paths:
      - "_drafts/**"

jobs:
  publish_drafts:
    runs-on: ubuntu-latest
    env:
      TZ: Australia/Sydney

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'

    - name: Check for published drafts
      id: check_published
      run: |
        if grep -rl "published: true" _drafts/*.md; then
          echo "found=true" >> $GITHUB_ENV
        else
          echo "found=false" >> $GITHUB_ENV
        fi

    - name: Skip if no drafts to publish
      if: env.found == 'false'
      run: echo "No drafts marked for publishing. Skipping."

    - name: Find drafts to publish
      if: env.found == 'true'
      run: |
        today=$(date +"%Y-%m-%d")
        mkdir -p _posts
        for file in _drafts/*.md; do
          if grep -q "published: true" "$file"; then
            filename=$(basename "$file")
            cp "$file" "_posts/${today}-${filename}" && echo "Copied $file to _posts/${today}-${filename}"
            rm "$file" && echo "Removed original draft file"
          fi
        done

    - name: Commit changes
      if: env.found == 'true'
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add _posts/*.md
        git add _drafts
        git commit -m "Auto-publish drafts on $(date +'%Y-%m-%d')"
        git push
